#ifndef BOARD_BASELINE_CONFIG_H
#define BOARD_BASELINE_CONFIG_H

#include "boards.h"
#include "nrfx_spim.h"
#include "uds_gateway.h"

#ifdef __cplusplus
extern "C" {
#endif

#define BOARD_BASELINE_PROFILE_SECURE 1U
#define BOARD_BASELINE_PROFILE_VULNERABLE 2U
#define BOARD_BASELINE_PROFILE_GATEWAY_SECURE 3U
#define BOARD_BASELINE_PROFILE_HOTPATCHED 4U
#define BOARD_BASELINE_PROFILE_KINTSUGI_RUNTIME 5U

#define BOARD_UDS_ECU_PROFILE_STRICT     1U
#define BOARD_UDS_ECU_PROFILE_VULNERABLE 2U

#ifndef BOARD_BASELINE_PROFILE
#define BOARD_BASELINE_PROFILE BOARD_BASELINE_PROFILE_SECURE
#endif

/*
 * Current MCP2515 wiring:
 *   P1.15 -> CLK/SCK
 *   P1.13 -> MOSI/SI
 *   P1.14 -> MISO/SO
 *   P1.12 -> CS
 *   P1.11 -> INT (reserved for interrupt-driven RX later)
 */
#define BOARD_MCP2515_SPI_INSTANCE_INDEX 3
#define BOARD_MCP2515_SPI_SCK_PIN        NRF_GPIO_PIN_MAP(1, 15)
#define BOARD_MCP2515_SPI_MOSI_PIN       NRF_GPIO_PIN_MAP(1, 13)
#define BOARD_MCP2515_SPI_MISO_PIN       NRF_GPIO_PIN_MAP(1, 14)
#define BOARD_MCP2515_SPI_CS_PIN         NRF_GPIO_PIN_MAP(1, 12)
#define BOARD_MCP2515_SPI_INT_PIN        NRF_GPIO_PIN_MAP(1, 11)
#define BOARD_MCP2515_SPI_FREQUENCY      NRF_SPIM_FREQ_1M

/*
 * Default timing is 250 kbps for board bring-up with the observed 8 MHz
 * MCP2515 crystal. 1 Mb/s and 500 kbps were tested earlier and still produced
 * transmit errors, so this profile matches the likely CANable test bitrate.
 *
 * Check the metal crystal can on the MCP2515 module. It is usually marked
 * "8.000" or "16.000". The active profile below assumes an 8 MHz module.
 */
#define BOARD_MCP2515_OSCILLATOR_HZ 8000000UL
#define BOARD_CAN_BITRATE_BPS       250000UL
#define BOARD_MCP2515_CNF1          0x00U
#define BOARD_MCP2515_CNF2          0xACU
#define BOARD_MCP2515_CNF3          0x03U

/* Alternative 8 MHz / 500 kbps profile:
 *   CNF1 = 0x00, CNF2 = 0x90, CNF3 = 0x82
 *
 * Alternative 16 MHz / 500 kbps profile:
 *   CNF1 = 0x00, CNF2 = 0xF0, CNF3 = 0x86
 */

#define BOARD_UDS_EXTERNAL_REQUEST_CAN_ID  0x7E0U
#define BOARD_UDS_EXTERNAL_RESPONSE_CAN_ID 0x7E8U
#define BOARD_UDS_INTERNAL_REQUEST_CAN_ID  0x7E1U
#define BOARD_UDS_INTERNAL_RESPONSE_CAN_ID 0x7E9U

#if (BOARD_BASELINE_PROFILE == BOARD_BASELINE_PROFILE_SECURE)
#define BOARD_BASELINE_PROFILE_NAME "secure"
#ifndef BOARD_UDS_GATEWAY_MODE
#define BOARD_UDS_GATEWAY_MODE UDS_GATEWAY_MODE_MISCONFIGURED
#endif
#ifndef BOARD_UDS_ECU_PROFILE
#define BOARD_UDS_ECU_PROFILE BOARD_UDS_ECU_PROFILE_STRICT
#endif
#elif (BOARD_BASELINE_PROFILE == BOARD_BASELINE_PROFILE_VULNERABLE)
#define BOARD_BASELINE_PROFILE_NAME "vulnerable"
#ifndef BOARD_UDS_GATEWAY_MODE
#define BOARD_UDS_GATEWAY_MODE UDS_GATEWAY_MODE_MISCONFIGURED
#endif
#ifndef BOARD_UDS_ECU_PROFILE
#define BOARD_UDS_ECU_PROFILE BOARD_UDS_ECU_PROFILE_VULNERABLE
#endif
#elif (BOARD_BASELINE_PROFILE == BOARD_BASELINE_PROFILE_GATEWAY_SECURE)
#define BOARD_BASELINE_PROFILE_NAME "gateway-secure"
#ifndef BOARD_UDS_GATEWAY_MODE
#define BOARD_UDS_GATEWAY_MODE UDS_GATEWAY_MODE_RESTRICTED
#endif
#ifndef BOARD_UDS_ECU_PROFILE
#define BOARD_UDS_ECU_PROFILE BOARD_UDS_ECU_PROFILE_STRICT
#endif
#elif (BOARD_BASELINE_PROFILE == BOARD_BASELINE_PROFILE_HOTPATCHED)
#define BOARD_BASELINE_PROFILE_NAME "hotpatched"
#ifndef BOARD_UDS_GATEWAY_MODE
#define BOARD_UDS_GATEWAY_MODE UDS_GATEWAY_MODE_MISCONFIGURED
#endif
#ifndef BOARD_UDS_ECU_PROFILE
#define BOARD_UDS_ECU_PROFILE BOARD_UDS_ECU_PROFILE_STRICT
#endif
#ifndef BOARD_UDS_APPLY_SECURITY_ACCESS_HOTPATCH
#define BOARD_UDS_APPLY_SECURITY_ACCESS_HOTPATCH 1
#endif
#elif (BOARD_BASELINE_PROFILE == BOARD_BASELINE_PROFILE_KINTSUGI_RUNTIME)
#define BOARD_BASELINE_PROFILE_NAME "kintsugi-runtime"
#ifndef BOARD_UDS_GATEWAY_MODE
#define BOARD_UDS_GATEWAY_MODE UDS_GATEWAY_MODE_MISCONFIGURED
#endif
#ifndef BOARD_UDS_ECU_PROFILE
#define BOARD_UDS_ECU_PROFILE BOARD_UDS_ECU_PROFILE_STRICT
#endif
#ifndef BOARD_UDS_KINTSUGI_BRIDGE_ENABLED
#define BOARD_UDS_KINTSUGI_BRIDGE_ENABLED 1
#endif
#else
#error "Unsupported BOARD_BASELINE_PROFILE"
#endif

#ifndef BOARD_UDS_APPLY_SECURITY_ACCESS_HOTPATCH
#define BOARD_UDS_APPLY_SECURITY_ACCESS_HOTPATCH 0
#endif
#ifndef BOARD_UDS_KINTSUGI_BRIDGE_ENABLED
#define BOARD_UDS_KINTSUGI_BRIDGE_ENABLED 0
#endif

#if (BOARD_UDS_ECU_PROFILE == BOARD_UDS_ECU_PROFILE_STRICT)
#define BOARD_UDS_ECU_PROFILE_NAME "strict"
#elif (BOARD_UDS_ECU_PROFILE == BOARD_UDS_ECU_PROFILE_VULNERABLE)
#define BOARD_UDS_ECU_PROFILE_NAME "vulnerable"
#else
#error "Unsupported BOARD_UDS_ECU_PROFILE"
#endif

#define BOARD_CAN_STARTUP_TEST_FRAME_ENABLED 1
#define BOARD_CAN_STARTUP_TEST_FRAME_DELAY_MS 1000U
#define BOARD_MCP2515_INTERNAL_LOOPBACK_SELF_TEST_ENABLED 1

#ifdef __cplusplus
}
#endif

#endif
